### ISSUE TITLE
Speed up action installation

### ISSUE THREAD

**Issue by fabiosangregorio** [sliteteam/github-action-git-crypt-unlock#3]
It currently takes 1m 30s on my build to install this action. Is there a way to speed this up, maybe by caching the docker build?

**Comment by fabiosangregorio** [comment]
Closing this since I'm not getting any activity.

**Comment by ArnaudRinquin** [comment]
@fabiosangregorio Sorry I missed that one entirely. Latest version (1.1.0) should speed this up!

**Comment by fabiosangregorio** [comment]
Hi @ArnaudRinquin , sorry but I'm currently using another action for git-crypt.
Just a careful note: I'm seeing a git-crypt in plaintext in your latest Github workflow, here: https://github.com/sliteteam/github-action-git-crypt-unlock/runs/796161382?check_suite_focus=true#step:5:3

**Comment by ArnaudRinquin** [comment]
Hi @fabiosangregorio 
Thanks for the head's up but it's normal it's visible as this test workflow isn't using a SECRET but an hardcoded value.
